// <auto-generated />
using System;
using DATA.ContextDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DATA.Migrations
{
    [DbContext(typeof(AuthenContext))]
    [Migration("20250623141927_new5")]
    partial class new5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DOMAIN.Model.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Utilisateur");
                });

            modelBuilder.Entity("DOMAIN.Model.Encadrant", b =>
                {
                    b.HasBaseType("DOMAIN.Model.Utilisateur");

                    b.Property<string>("Poste")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Encadrant");
                });

            modelBuilder.Entity("DOMAIN.Model.RH", b =>
                {
                    b.HasBaseType("DOMAIN.Model.Utilisateur");

                    b.Property<string>("Departement")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("RH");
                });

            modelBuilder.Entity("DOMAIN.Model.Stagiaire", b =>
                {
                    b.HasBaseType("DOMAIN.Model.Utilisateur");

                    b.Property<bool>("IsAffected")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Stagiaire");
                });
#pragma warning restore 612, 618
        }
    }
}
