//// <auto-generated />
//using System;
//using DATA.ContextDb;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//namespace DATA.Migrations
//{
//    [DbContext(typeof(AuthenContext))]
//    [Migration("20250623092834_mg2")]
//    partial class mg2
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "3.1.1")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128)
//                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//            modelBuilder.Entity("DOMAIN.Model.Utilisateur", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("Email")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("MotDePasse")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Nom")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(50)")
//                        .HasMaxLength(50);

//                    b.Property<string>("Prenom")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(50)")
//                        .HasMaxLength(50);

//                    b.Property<string>("Role")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Utilisateurs");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
